---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {node_name}
  labels:
    name: {node_name}
    app: tendermint
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tendermint
  template:
    metadata:
      labels:
        app: tendermint
        name: {node_name}
    spec:
      containers:
      - name: {node_name}
        image: {image}
        imagePullPolicy: Always
        command:
          - /tendermint/tendermint
        args:
          - start
          - --proxy_app=persistent_kvstore
          - --p2p.persistent_peers={peers}
        #   - node
        env:
          - name: ID
            value: "{id}"
          - name: LOG
            value: "{log}"
          - name: BINARY
            value: "/tendermint/tendermint"
        volumeMounts:
          - mountPath: /root/.tendermint/config
            name: vol{id}
            subPath: tendermint/{node_name}/config          
          - mountPath: /root/.tendermint/data
            name: vol{id}
            subPath: tendermint/{node_name}/data
        resources:
          requests:
            cpu: "1"
            memory: 2Gi
          limits:
           cpu: "1"
           memory: 2Gi
      volumes:
        - name: vol{id}
          persistentVolumeClaim:
            claimName: tendermint
---
kind: Service
apiVersion: v1
metadata:
  name:  {node_name}
  labels:
    name: {node_name}
    app: tendermint
spec:
  selector:
    name: {node_name}
  type:  ClusterIP
  clusterIP: {ip_addr}
  ports:
  - name:  default
    port:  42
    targetPort:  42
  - name:  p6
    port:  26656
    targetPort:  26656
  - name:  p7
    port:  26657
    targetPort:  26657