---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {node_name}
  labels:
    name: {node_name}
    app: chainBFT
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chainBFT
  template:
    metadata:
      labels:
        app: chainBFT
        name: {node_name}
    spec:
      containers:
      - name: {node_name}
        image: {image}
        imagePullPolicy: Always
        command:
          - chain_bft
        args:
          - start
          - node
          - --p2p.persistent_peers={peers}
          - --consensus.slot_timeout={slot_timeout}
          - --mempool.default_block_size={tx_num}
          - --consensus.view_change_interval={vc_interval}
          - --consensus.byzantine_strategy={byzantine_strategy}
        volumeMounts:
          - mountPath: /chain_bft/.chainBFT/config
            name: vol{id}
            subPath: test/{node_name}/config          
          - mountPath: /chain_bft/.chainBFT/data
            name: vol{id}
            subPath: test/{node_name}/data
          - name: date-config
            mountPath: /etc/localtime
        # resources:
        #   requests:
        #     cpu: "1"
        #     memory: 2Gi
        #   limits:
        #    cpu: "1"
        #    memory: 2Gi
      volumes:
        - name: vol{id}
          persistentVolumeClaim:
            claimName: cbft
        - name: date-config
          hostPath:
            path: /etc/localtime
---
kind: Service
apiVersion: v1
metadata:
  name:  {node_name}
  labels:
    name: {node_name}
    app: chainBFT
spec:
  selector:
    name: {node_name}
  type:  ClusterIP
  clusterIP: {ip_addr}
  ports:
  - name:  default
    port:  42
    targetPort:  42
  - name:  p6
    port:  26656
    targetPort:  26656
  - name:  p7
    port:  26657
    targetPort:  26657
  - name:  profile
    port:  8080
    targetPort:  8080